### ISSUE TITLE
Alert box remains persistent

### ISSUE THREAD

**Issue by bug-author** [Harry260/youtube-md#1]
After copying the generated markdown, the alert box that says copied to clipboard remains persistent even on pressing OK.

**Comment by Harry260** [comment]
I didn't understand what you mean.. But the **Alert box** disappears after pressing <code>OK</code>

![Youtube embed for markdown - YouTube-md - Google Chrome 2022-08-16 20-36-19](https://user-images.githubusercontent.com/61614900/184914287-c997f4df-d48f-4c7b-915e-d191f9c52cfc.gif)

**Comment by bug-author** [comment]
This might help.

[screen-capture.webm](https://user-images.githubusercontent.com/48406637/184943428-6b2231c1-eeb1-47d7-8a31-126f33b3bd38.webm)

**Comment by Harry260** [comment]
Fixed it ! 6899547dd8049898d139fcf44258eaabc83c3e62
